version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apk add --no-cache bash curl jq unzip docker terraform
      - echo "Verifying installations..."
      - terraform --version
      - docker --version
  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPO_NAME=fiap-34cld-app-ecs
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPO_NAME:$IMAGE_TAG .
      - docker tag $REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REP
