version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - curl -sLO https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform_1.6.0_linux_amd64.zip -d /usr/local/bin/
  pre_build:
    commands:
      - echo "Listing files in the current directory:"
      - pwd
      - ls -la
      - echo "running cd terraform"
      - cd terraform
      - echo "running terraform init"
      - terraform init
  build:
    commands:
      - echo "Running Terraform Plan..."
      - terraform plan -out=tfplan
      - echo Applying Terraform Changes...
      - terraform apply -auto-approve tfplan
artifacts:
  files: []
