version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x  # Optional: Use if you need Python; adjust accordingly
    commands:
      - echo "Installing Terraform"
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - rm terraform.zip
      - terraform --version

  pre_build:
    commands:
      - echo "Initializing Terraform"
      - terraform init

  build:
    commands:
      - echo "Running Terraform commands"
      # Add your Terraform commands below
      # For example:
      - terraform plan

  post_build:
    commands:
      - echo "Terraform build completed successfully"

artifacts:
  files:
    - '**/*'  # Adjust this to specify artifacts to upload, if any