version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - curl -sLO https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform_1.6.0_linux_amd64.zip -d /usr/local/bin/
  pre_build:
    commands:
      - echo "Listing files in the current directory:"
      - pwd
      - ls -la
  build:
  commands:
    - echo "Listing files in the 'terraform' directory:"
    - ls -la terraform
    - cd terraform
    - terraform init
    - terraform plan -out=tfplan
    - terraform apply -auto-approve tfplan
artifacts:
  files: []
